### ISSUE TITLE
Get 415 error when bom file is too large

### ISSUE THREAD

**Issue by leichen-eizo** [DependencyTrack/gh-upload-sbom#31] opened 2024-06-18 05:35 UTC
When upload bom get a  415 error.

It may due to the limit of put
```
The maximum allowed length of the bom value is 20'000'000 characters. When uploading large BOMs, the POST endpoint is preferred, as it does not have this limit.

Requires permission BOM_UPLOAD
```

Can you change the PUT into POST?

https://github.com/DependencyTrack/gh-upload-sbom/blob/1f0526714a54aeb1cdf780889cf1e917c477d775/index.js#L77

**Comment by nscuro** [comment] 2024-08-26 20:14
Duplicate of #7

**Closed by nscuro** 2024-08-26 20:14 UTC
Labels: duplicate
